name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 8 * * *"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: master

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.20.3
          run_install: |
            - recursive: false
              args: [--no-frozen-lockfile]

      - name: Install and Build
        run: |
          pnpm run graphql-codegen
          pnpm run build
          pnpm run sitemap
          pnpm run export
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          GRAPHCMS_PROJECT_API: ${{ secrets.GRAPHCMS_PROJECT_API }}

      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: out
