name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 8 * * *"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: master

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
          run_install: true

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yml"

      - name: Install and Build
        run: |
          pnpm install
          pnpm run graphql-codegen
          pnpm run build
          pnpm run sitemap
          pnpm run export
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          GRAPHCMS_PROJECT_API: ${{ secrets.GRAPHCMS_PROJECT_API }}

      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: out
