name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
          run_install: |
            - recursive: false
              args: [--no-frozen-lockfile]

      - name: pnpm install and lint
        run: |
          pnpm install
          pnpm run graphql-codegen
          pnpm run lint
