name: Mutation Test

on: []

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
          run_install: true

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yml"

      - name: pnpm install and test
        run: |
          pnpm install
          pnpm run mutation-test
