name: Mutation Test

on: []

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 6.20.3
          run_install: |
            - recursive: false
              args: [--no-frozen-lockfile]

      - name: pnpm install and test
        run: |
          pnpm run mutation-test
