name: Size Limit

on:
  pull_request:
    branches:
      - master

jobs:
  size:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - uses: pnpm/action-setup@v2.2.3
        with:
          run_install: false
          version: 6.20.3

      - uses: andresz1/size-limit-action@v1
        env:
          SKIP_SENTRY: "true"
          GRAPHCMS_PROJECT_API: "https://api-us-east-1.graphcms.com/v2/ckswjodgd0syb01xr1ayu7841/master"
          CI_JOB_NUMBER: 1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: size-build
