name: Size Limit

on:
  pull_request:
    branches:
    - master

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - uses: andresz1/size-limit-action@v1
        env:
          SKIP_SENTRY: "true"
          GRAPHCMS_PROJECT_API: "https://api-us-east-1.graphcms.com/v2/ckswjodgd0syb01xr1ayu7841/master"
          CI_JOB_NUMBER: 1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: size-build
