name: Size Limit

on:
  pull_request:
    branches:
      - master

jobs:
    size:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - uses: andresz1/size-limit-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: |
            npm run graphql-codegen
            npm run build
            npm run sitemap
            npm run export
        env:
          SKIP_SENTRY: "true"
          GRAPHCMS_PROJECT_API: ${{ secrets.GRAPHCMS_PROJECT_API }}
