name: Typecheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.20.3
          run_install: |
            - recursive: false
              args: [--no-frozen-lockfile]

      - name: pnpm install and lint
        run: |
          pnpm run graphql-codegen
          pnpm run ts
        env:
          SKIP_SENTRY: "true"
          GRAPHCMS_PROJECT_API: ${{ secrets.GRAPHCMS_PROJECT_API }}
