name: Typecheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: "package-lock.json"

      - name: pnpm install and lint
        run: |
          pnpm install
          pnpm run graphql-codegen
          pnpm run ts
        env:
          SKIP_SENTRY: "true"
          GRAPHCMS_PROJECT_API: ${{ secrets.GRAPHCMS_PROJECT_API }}
